//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Interview {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Header", typeof(InterviewHeader), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("Patients", typeof(InterviewPatients), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewHeader {
    
    private string transactionIdField;
    
    private string transactionTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionId {
        get {
            return this.transactionIdField;
        }
        set {
            this.transactionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewPatients {
    
    private InterviewPatientsPatient[] patientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Patient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterviewPatientsPatient[] Patient {
        get {
            return this.patientField;
        }
        set {
            this.patientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewPatientsPatient {
    
    private InterviewPatientsPatientBasic[] basicField;
    
    private InterviewPatientsPatientNextOfKin[] nextOfKinField;
    
    private InterviewPatientsPatientGpDetails[] gpDetailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Basic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterviewPatientsPatientBasic[] Basic {
        get {
            return this.basicField;
        }
        set {
            this.basicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NextOfKin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterviewPatientsPatientNextOfKin[] NextOfKin {
        get {
            return this.nextOfKinField;
        }
        set {
            this.nextOfKinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GpDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public InterviewPatientsPatientGpDetails[] GpDetails {
        get {
            return this.gpDetailsField;
        }
        set {
            this.gpDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewPatientsPatientBasic {
    
    private string pasNumberField;
    
    private string forenamesField;
    
    private string surnameField;
    
    private string dateOfBirthField;
    
    private string sexCodeField;
    
    private string homeTelephoneNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PasNumber {
        get {
            return this.pasNumberField;
        }
        set {
            this.pasNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Forenames {
        get {
            return this.forenamesField;
        }
        set {
            this.forenamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DateOfBirth {
        get {
            return this.dateOfBirthField;
        }
        set {
            this.dateOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SexCode {
        get {
            return this.sexCodeField;
        }
        set {
            this.sexCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HomeTelephoneNumber {
        get {
            return this.homeTelephoneNumberField;
        }
        set {
            this.homeTelephoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewPatientsPatientNextOfKin {
    
    private string nokNameField;
    
    private string nokRelationshipCodeField;
    
    private string nokAddressLine1Field;
    
    private string nokAddressLine2Field;
    
    private string nokAddressLine3Field;
    
    private string nokAddressLine4Field;
    
    private string nokPostcodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokName {
        get {
            return this.nokNameField;
        }
        set {
            this.nokNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokRelationshipCode {
        get {
            return this.nokRelationshipCodeField;
        }
        set {
            this.nokRelationshipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokAddressLine1 {
        get {
            return this.nokAddressLine1Field;
        }
        set {
            this.nokAddressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokAddressLine2 {
        get {
            return this.nokAddressLine2Field;
        }
        set {
            this.nokAddressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokAddressLine3 {
        get {
            return this.nokAddressLine3Field;
        }
        set {
            this.nokAddressLine3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokAddressLine4 {
        get {
            return this.nokAddressLine4Field;
        }
        set {
            this.nokAddressLine4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NokPostcode {
        get {
            return this.nokPostcodeField;
        }
        set {
            this.nokPostcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class InterviewPatientsPatientGpDetails {
    
    private string gpCodeField;
    
    private string gpSurnameField;
    
    private string gpInitialsField;
    
    private string gpPhoneField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GpCode {
        get {
            return this.gpCodeField;
        }
        set {
            this.gpCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GpSurname {
        get {
            return this.gpSurnameField;
        }
        set {
            this.gpSurnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GpInitials {
        get {
            return this.gpInitialsField;
        }
        set {
            this.gpInitialsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GpPhone {
        get {
            return this.gpPhoneField;
        }
        set {
            this.gpPhoneField = value;
        }
    }
}
