//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace PersistXML.Xml
{ // 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot( Namespace = "", IsNullable = false, ElementName = "Interview" )]
    public partial class XmlInterview {
    
        private object[] itemsField;
    
        /// <remarks/>
        [XmlElement("Header", typeof(XmlHeader), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElement("Patients", typeof(XmlPatients), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlHeader {
    
        private string transactionIdField;
    
        private string transactionTimeField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionTime {
            get {
                return this.transactionTimeField;
            }
            set {
                this.transactionTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlPatients {
    
        private XmlPatient[] patientField;
    
        /// <remarks/>
        [XmlElement("Patient", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlPatient[] Patient {
            get {
                return this.patientField;
            }
            set {
                this.patientField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlPatient {
    
        private XmlPatientBasic[] basicField;
    
        private XmlNextOfKin[] nextOfKinField;
    
        private XmlGpDetails[] gpDetailsField;
    
        /// <remarks/>
        [XmlElement("Basic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlPatientBasic[] Basic {
            get {
                return this.basicField;
            }
            set {
                this.basicField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("NextOfKin", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlNextOfKin[] NextOfKin {
            get {
                return this.nextOfKinField;
            }
            set {
                this.nextOfKinField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("GpDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlGpDetails[] GpDetails {
            get {
                return this.gpDetailsField;
            }
            set {
                this.gpDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlPatientBasic {
    
        private string pasNumberField;
    
        private string forenamesField;
    
        private string surnameField;
    
        private string dateOfBirthField;
    
        private string sexCodeField;
    
        private string homeTelephoneNumberField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasNumber {
            get {
                return this.pasNumberField;
            }
            set {
                this.pasNumberField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Forenames {
            get {
                return this.forenamesField;
            }
            set {
                this.forenamesField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SexCode {
            get {
                return this.sexCodeField;
            }
            set {
                this.sexCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HomeTelephoneNumber {
            get {
                return this.homeTelephoneNumberField;
            }
            set {
                this.homeTelephoneNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlNextOfKin {
    
        private string nokNameField;
    
        private string nokRelationshipCodeField;
    
        private string nokAddressLine1Field;
    
        private string nokAddressLine2Field;
    
        private string nokAddressLine3Field;
    
        private string nokAddressLine4Field;
    
        private string nokPostcodeField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokName {
            get {
                return this.nokNameField;
            }
            set {
                this.nokNameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokRelationshipCode {
            get {
                return this.nokRelationshipCodeField;
            }
            set {
                this.nokRelationshipCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokAddressLine1 {
            get {
                return this.nokAddressLine1Field;
            }
            set {
                this.nokAddressLine1Field = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokAddressLine2 {
            get {
                return this.nokAddressLine2Field;
            }
            set {
                this.nokAddressLine2Field = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokAddressLine3 {
            get {
                return this.nokAddressLine3Field;
            }
            set {
                this.nokAddressLine3Field = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokAddressLine4 {
            get {
                return this.nokAddressLine4Field;
            }
            set {
                this.nokAddressLine4Field = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NokPostcode {
            get {
                return this.nokPostcodeField;
            }
            set {
                this.nokPostcodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlGpDetails {
    
        private string gpCodeField;
    
        private string gpSurnameField;
    
        private string gpInitialsField;
    
        private string gpPhoneField;
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GpCode {
            get {
                return this.gpCodeField;
            }
            set {
                this.gpCodeField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GpSurname {
            get {
                return this.gpSurnameField;
            }
            set {
                this.gpSurnameField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GpInitials {
            get {
                return this.gpInitialsField;
            }
            set {
                this.gpInitialsField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GpPhone {
            get {
                return this.gpPhoneField;
            }
            set {
                this.gpPhoneField = value;
            }
        }
    }
}